version: '3.7'

services:
#   backend:
#     image: tennis-ai-back:prod
#     networks:
#       - backend

  frontend:
    image: tennis-ai-front:prod
    ports:
      - "3000:3000"
#     environment:
#       - BACKEND_URL=http://backend:8080
#     depends_on:
#       - backend

# networks:
#   backend: