services:
  frontend:
    build:
      context: ../..
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=8000
  backend:
    image: hsndocker/tennis-ai-backend-prod:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=db_user
      - DATABASE_PASSWORD=db_password
      - DATABASE_NAME=tennis
      - DATABASE_PORT=5432
    command: /bin/sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  db:
    image: postgres:alpine3.19
    environment:
      POSTGRES_DB: tennis
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5432:5432"
    volumes:
      - tennis_ai_postgres_prod:/var/lib/postgresql/data
volumes:
  tennis_ai_postgres_prod:
